
[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express-oauth2-jwt-bearer", "mongodb", "mongoose"]

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/api/resources"
  to = "/.netlify/functions/getResources"
  status = 200

[[redirects]]
  from = "/api/resources/:id"
  to = "/.netlify/functions/getResource/:id"
  status = 200

[[redirects]]
  from = "/api/resources"
  to = "/.netlify/functions/createResource"
  status = 200
  methods = ["POST"]

[[redirects]]
  from = "/api/resources/:id"
  to = "/.netlify/functions/updateResource/:id"
  status = 200
  methods = ["PUT"]

[[redirects]]
  from = "/api/resources/:id"
  to = "/.netlify/functions/deleteResource/:id"
  status = 200
  methods = ["DELETE"]

[[redirects]]
  from = "/api/resources/:id/:direction"
  to = "/.netlify/functions/moveResource/:id/:direction"
  status = 200
  methods = ["PATCH"]

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/getCategories"
  status = 200

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/addCategory"
  status = 200
  methods = ["POST"]

[[redirects]]
  from = "/api/categories/:id"
  to = "/.netlify/functions/updateCategory/:id"
  status = 200
  methods = ["PUT"]

[[redirects]]
  from = "/api/categories/:id"
  to = "/.netlify/functions/deleteCategory/:id"
  status = 200
  methods = ["DELETE"]

[[redirects]]
  from = "/api/categories/:id/:direction"
  to = "/.netlify/functions/moveCategory/:id/:direction"
  status = 200
  methods = ["PATCH"]

[[redirects]]
  from = "/api/subcategories"
  to = "/.netlify/functions/getSubCategories"
  status = 200

[[redirects]]
  from = "/api/subcategories"
  to = "/.netlify/functions/addSubCategory"
  status = 200
  methods = ["POST"]

[[redirects]]
  from = "/api/subcategories/:id"
  to = "/.netlify/functions/updateSubCategory/:id"
  status = 200
  methods = ["PUT"]

[[redirects]]
  from = "/api/subcategories/:id"
  to = "/.netlify/functions/deleteSubCategory/:id"
  status = 200
  methods = ["DELETE"]

[[redirects]]
  from = "/api/subcategories/:id/:direction"
  to = "/.netlify/functions/moveSubCategory/:id/:direction"
  status = 200
  methods = ["PATCH"]


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"